// Shared data for drivers, teams, and news across the site

export const teams = [
  {
    id: "red-bull",
    name: "Oracle Red Bull Racing",
    shortName: "Red Bull",
    country: "Austria",
    countryFlag: "🇦🇹",
    base: "Milton Keynes, United Kingdom",
    teamPrincipal: "Christian Horner",
    technicalChief: "Pierre Waché",
    chassis: "RB21",
    powerUnit: "Honda RBPT",
    firstEntry: 2005,
    championships: 7,
    wins: 120,
    poles: 103,
    fastestLaps: 95,
    color: "#1E41FF",
    secondaryColor: "#FFD700",
    logo: "/red-bull-racing-f1-logo.jpg",
    carImage: "/red-bull-rb21-f1-car-blue-livery.jpg",
    description:
      "Red Bull Racing, officially Oracle Red Bull Racing, is one of two Formula One teams owned by the Red Bull beverage company. The Austrian outfit has dominated the sport in recent years, winning four consecutive championships with Max Verstappen.",
    achievements: [
      "2010-2013 Constructor Champions",
      "2021-2024 Constructor Champions",
      "Most dominant season in F1 history (2023)",
    ],
  },
  {
    id: "ferrari",
    name: "Scuderia Ferrari",
    shortName: "Ferrari",
    country: "Italy",
    countryFlag: "🇮🇹",
    base: "Maranello, Italy",
    teamPrincipal: "Frédéric Vasseur",
    technicalChief: "Loïc Serra",
    chassis: "SF-25",
    powerUnit: "Ferrari",
    firstEntry: 1950,
    championships: 16,
    wins: 245,
    poles: 251,
    fastestLaps: 262,
    color: "#DC0000",
    secondaryColor: "#FFF200",
    logo: "/scuderia-ferrari-f1-logo.jpg",
    carImage: "/ferrari-sf-25-f1-car-red-livery.jpg",
    description:
      "Scuderia Ferrari is the racing division of luxury Italian auto manufacturer Ferrari and the most successful team in Formula One history. The Prancing Horse has been a part of F1 since its inception in 1950.",
    achievements: [
      "Most Constructor Championships (16)",
      "Most race victories (245+)",
      "Only team to compete in every F1 season",
    ],
  },
  {
    id: "mclaren",
    name: "McLaren Formula 1 Team",
    shortName: "McLaren",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    base: "Woking, United Kingdom",
    teamPrincipal: "Andrea Stella",
    technicalChief: "Peter Prodromou",
    chassis: "MCL39",
    powerUnit: "Mercedes",
    firstEntry: 1966,
    championships: 8,
    wins: 188,
    poles: 159,
    fastestLaps: 165,
    color: "#FF8000",
    secondaryColor: "#0090D0",
    logo: "/mclaren-f1-team-logo.jpg",
    carImage: "/mclaren-mcl39-f1-car-papaya-orange-livery.jpg",
    description:
      "McLaren Racing is one of the most successful teams in Formula One history. Founded by New Zealand racing legend Bruce McLaren, the team has won multiple championships and produced legendary drivers.",
    achievements: ["8 Constructor Championships", "12 Driver Championships", "Ayrton Senna's iconic team (1988-1993)"],
  },
  {
    id: "mercedes",
    name: "Mercedes-AMG Petronas F1 Team",
    shortName: "Mercedes",
    country: "Germany",
    countryFlag: "🇩🇪",
    base: "Brackley, United Kingdom",
    teamPrincipal: "Toto Wolff",
    technicalChief: "James Allison",
    chassis: "W16",
    powerUnit: "Mercedes",
    firstEntry: 2010,
    championships: 8,
    wins: 125,
    poles: 136,
    fastestLaps: 98,
    color: "#00D2BE",
    secondaryColor: "#000000",
    logo: "/mercedes-amg-petronas-f1-logo.jpg",
    carImage: "/mercedes-w16-f1-car-silver-arrows-livery.jpg",
    description:
      "Mercedes-AMG Petronas F1 Team dominated Formula One from 2014 to 2021, winning eight consecutive Constructors' Championships. The Silver Arrows continue to be a front-running team.",
    achievements: [
      "8 consecutive Constructor titles (2014-2021)",
      "Lewis Hamilton's 6 championships",
      "Most dominant turbo-hybrid era team",
    ],
  },
  {
    id: "aston-martin",
    name: "Aston Martin Aramco F1 Team",
    shortName: "Aston Martin",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    base: "Silverstone, United Kingdom",
    teamPrincipal: "Mike Krack",
    technicalChief: "Dan Fallows",
    chassis: "AMR25",
    powerUnit: "Mercedes",
    firstEntry: 2021,
    championships: 0,
    wins: 0,
    poles: 1,
    fastestLaps: 3,
    color: "#006F62",
    secondaryColor: "#CEDC00",
    logo: "/aston-martin-f1-logo.jpg",
    carImage: "/aston-martin-amr25-f1-car-green-livery.jpg",
    description:
      "Aston Martin Aramco F1 Team is a British constructor that returned to Formula One in 2021. With significant investment and the signing of Fernando Alonso, the team has ambitious plans.",
    achievements: [
      "Fernando Alonso podium streak (2023)",
      "Major factory expansion underway",
      "Adrian Newey joining 2025",
    ],
  },
  {
    id: "alpine",
    name: "BWT Alpine F1 Team",
    shortName: "Alpine",
    country: "France",
    countryFlag: "🇫🇷",
    base: "Enstone, United Kingdom",
    teamPrincipal: "Oliver Oakes",
    technicalChief: "David Sanchez",
    chassis: "A525",
    powerUnit: "Renault",
    firstEntry: 2021,
    championships: 2,
    wins: 21,
    poles: 20,
    fastestLaps: 15,
    color: "#FF87BC",
    secondaryColor: "#0090FF",
    logo: "/alpine-f1-team-logo.jpg",
    carImage: "/alpine-a525-f1-car-pink-blue-livery.jpg",
    description:
      "Alpine F1 Team represents the French manufacturer Renault's works effort in Formula One. Racing under the Alpine brand since 2021, the team has a rich history including back-to-back titles in 2005-2006.",
    achievements: [
      "2005-2006 Constructor Champions (as Renault)",
      "Fernando Alonso's championship-winning team",
      "French manufacturer heritage",
    ],
  },
  {
    id: "williams",
    name: "Williams Racing",
    shortName: "Williams",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    base: "Grove, United Kingdom",
    teamPrincipal: "James Vowles",
    technicalChief: "Pat Fry",
    chassis: "FW47",
    powerUnit: "Mercedes",
    firstEntry: 1977,
    championships: 9,
    wins: 114,
    poles: 128,
    fastestLaps: 133,
    color: "#005AFF",
    secondaryColor: "#00A0DE",
    logo: "/williams-racing-f1-logo.jpg",
    carImage: "/williams-fw47-f1-car-blue-livery.jpg",
    description:
      "Williams Racing is one of the most successful teams in Formula One history, with nine Constructors' titles. Founded by Sir Frank Williams, the team is rebuilding under new leadership.",
    achievements: [
      "9 Constructor Championships",
      "7 Driver Championships",
      "Legendary partnerships with Mansell, Prost, Hill",
    ],
  },
  {
    id: "rb",
    name: "Visa Cash App Racing Bulls",
    shortName: "RB",
    country: "Italy",
    countryFlag: "🇮🇹",
    base: "Faenza, Italy",
    teamPrincipal: "Laurent Mekies",
    technicalChief: "Jody Egginton",
    chassis: "VCARB 02",
    powerUnit: "Honda RBPT",
    firstEntry: 2006,
    championships: 0,
    wins: 2,
    poles: 1,
    fastestLaps: 3,
    color: "#6692FF",
    secondaryColor: "#FFFFFF",
    logo: "/placeholder.svg?height=100&width=200",
    carImage: "/placeholder.svg?height=400&width=800",
    description:
      "Visa Cash App Racing Bulls, formerly AlphaTauri and Toro Rosso, serves as Red Bull's junior team. The Italian-based outfit has developed numerous talents including Max Verstappen and Sebastian Vettel.",
    achievements: [
      "Sebastian Vettel's Monza victory (2008)",
      "Pierre Gasly's Monza victory (2020)",
      "Young driver development success",
    ],
  },
  {
    id: "sauber",
    name: "Stake F1 Team Kick Sauber",
    shortName: "Sauber",
    country: "Switzerland",
    countryFlag: "🇨🇭",
    base: "Hinwil, Switzerland",
    teamPrincipal: "Mattia Binotto",
    technicalChief: "James Key",
    chassis: "C45",
    powerUnit: "Ferrari",
    firstEntry: 1993,
    championships: 0,
    wins: 1,
    poles: 1,
    fastestLaps: 5,
    color: "#52E252",
    secondaryColor: "#000000",
    logo: "/placeholder.svg?height=100&width=200",
    carImage: "/placeholder.svg?height=400&width=800",
    description:
      "Sauber is transitioning to become the Audi works team from 2026. The Swiss team has a long history in F1 and has produced talents like Kimi Räikkönen and Sebastian Vettel.",
    achievements: [
      "Robert Kubica's maiden victory (2008, as BMW Sauber)",
      "Launching pad for future champions",
      "Becoming Audi works team (2026)",
    ],
  },
  {
    id: "haas",
    name: "MoneyGram Haas F1 Team",
    shortName: "Haas",
    country: "United States",
    countryFlag: "🇺🇸",
    base: "Kannapolis, United States",
    teamPrincipal: "Ayao Komatsu",
    technicalChief: "Andrea De Zordo",
    chassis: "VF-25",
    powerUnit: "Ferrari",
    firstEntry: 2016,
    championships: 0,
    wins: 0,
    poles: 1,
    fastestLaps: 2,
    color: "#FFFFFF",
    secondaryColor: "#B6BABD",
    logo: "/placeholder.svg?height=100&width=200",
    carImage: "/placeholder.svg?height=400&width=800",
    description:
      "Haas F1 Team is the first American constructor to compete in Formula One since 1986. Founded by Gene Haas, the team has steadily improved since its debut in 2016.",
    achievements: [
      "First American F1 team in 30 years",
      "Points on debut (2016)",
      "Kevin Magnussen pole position (2022)",
    ],
  },
]

export const allDrivers = [
  {
    id: "max-verstappen",
    number: 1,
    firstName: "Max",
    lastName: "Verstappen",
    team: "Red Bull Racing",
    teamId: "red-bull",
    country: "Netherlands",
    countryFlag: "🇳🇱",
    dateOfBirth: "September 30, 1997",
    placeOfBirth: "Hasselt, Belgium",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#1E41FF",
    stats: { wins: 62, poles: 40, championships: 4, podiums: 111, fastestLaps: 33, points: 2985 },
    careerHighlights: [
      "4x World Champion (2021, 2022, 2023, 2024)",
      "Youngest race winner in F1 history",
      "Record 19 wins in a season (2023)",
    ],
    bio: "Max Verstappen is a four-time Formula One World Champion, cementing his place among the all-time greats. Known for his aggressive driving style and racecraft, the Dutchman has dominated the sport since his first title in 2021.",
  },
  {
    id: "lando-norris",
    number: 4,
    firstName: "Lando",
    lastName: "Norris",
    team: "McLaren",
    teamId: "mclaren",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    dateOfBirth: "November 13, 1999",
    placeOfBirth: "Bristol, England",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FF8000",
    stats: { wins: 4, poles: 8, championships: 0, podiums: 26, fastestLaps: 9, points: 1012 },
    careerHighlights: ["First F1 win at Miami 2024", "Championship contender 2024", "Multiple sprint race victories"],
    bio: "Lando Norris has established himself as one of the brightest talents in Formula One. The British driver's combination of raw speed and consistency has made him a championship contender.",
  },
  {
    id: "charles-leclerc",
    number: 16,
    firstName: "Charles",
    lastName: "Leclerc",
    team: "Ferrari",
    teamId: "ferrari",
    country: "Monaco",
    countryFlag: "🇲🇨",
    dateOfBirth: "October 16, 1997",
    placeOfBirth: "Monte Carlo, Monaco",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#DC0000",
    stats: { wins: 8, poles: 26, championships: 0, podiums: 40, fastestLaps: 10, points: 1254 },
    careerHighlights: ["Monaco GP winner (2024)", "Most poles in a single season for Ferrari", "F2 Champion (2017)"],
    bio: "Charles Leclerc is Ferrari's golden boy and one of the fastest qualifiers on the grid. The Monegasque driver's smooth driving style and tire management make him a threat every race weekend.",
  },
  {
    id: "oscar-piastri",
    number: 81,
    firstName: "Oscar",
    lastName: "Piastri",
    team: "McLaren",
    teamId: "mclaren",
    country: "Australia",
    countryFlag: "🇦🇺",
    dateOfBirth: "April 6, 2001",
    placeOfBirth: "Melbourne, Australia",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FF8000",
    stats: { wins: 3, poles: 2, championships: 0, podiums: 15, fastestLaps: 3, points: 456 },
    careerHighlights: ["First win at Hungary 2024", "F2 Champion (2021)", "F3 Champion (2020)"],
    bio: "Oscar Piastri burst onto the F1 scene as one of the most hyped rookies in recent memory. The Australian delivered on expectations, winning races in just his second season.",
  },
  {
    id: "carlos-sainz",
    number: 55,
    firstName: "Carlos",
    lastName: "Sainz",
    team: "Williams",
    teamId: "williams",
    country: "Spain",
    countryFlag: "🇪🇸",
    dateOfBirth: "September 1, 1994",
    placeOfBirth: "Madrid, Spain",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#005AFF",
    stats: { wins: 4, poles: 6, championships: 0, podiums: 25, fastestLaps: 5, points: 1148 },
    careerHighlights: [
      "First win at Silverstone 2022",
      "Australia GP winner 2024",
      "Son of rally legend Carlos Sainz Sr.",
    ],
    bio: "Carlos Sainz Jr. is a consistent performer known for his racecraft and tire management. The Spaniard moves to Williams for 2025 after successful stints at Ferrari and McLaren.",
  },
  {
    id: "lewis-hamilton",
    number: 44,
    firstName: "Lewis",
    lastName: "Hamilton",
    team: "Ferrari",
    teamId: "ferrari",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    dateOfBirth: "January 7, 1985",
    placeOfBirth: "Stevenage, England",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#DC0000",
    stats: { wins: 105, poles: 104, championships: 7, podiums: 202, fastestLaps: 67, points: 4829 },
    careerHighlights: [
      "Joint-most World Championships (7)",
      "Most race wins in F1 history (105)",
      "Historic move to Ferrari (2025)",
    ],
    bio: "Sir Lewis Hamilton is one of the greatest drivers in Formula One history. The seven-time World Champion has broken nearly every record in the sport and makes a historic move to Ferrari for 2025.",
  },
  {
    id: "george-russell",
    number: 63,
    firstName: "George",
    lastName: "Russell",
    team: "Mercedes",
    teamId: "mercedes",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    dateOfBirth: "February 15, 1998",
    placeOfBirth: "King's Lynn, England",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#00D2BE",
    stats: { wins: 3, poles: 5, championships: 0, podiums: 18, fastestLaps: 8, points: 578 },
    careerHighlights: ["First win at Brazil 2022", "F2 Champion (2018)", "Mercedes team leader (2025)"],
    bio: "George Russell is Mercedes' future star and now team leader following Hamilton's departure. Known as 'Mr. Saturday' for his qualifying prowess, the Briton is ready to lead the Silver Arrows.",
  },
  {
    id: "fernando-alonso",
    number: 14,
    firstName: "Fernando",
    lastName: "Alonso",
    team: "Aston Martin",
    teamId: "aston-martin",
    country: "Spain",
    countryFlag: "🇪🇸",
    dateOfBirth: "July 29, 1981",
    placeOfBirth: "Oviedo, Spain",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#006F62",
    stats: { wins: 32, poles: 22, championships: 2, podiums: 106, fastestLaps: 26, points: 2329 },
    careerHighlights: [
      "2x World Champion (2005, 2006)",
      "8 podiums in first Aston Martin season",
      "Most race starts in F1 history",
    ],
    bio: "Fernando Alonso is a Formula One legend who continues to defy age. The two-time World Champion's passion and skill remain undiminished as he chases a third title with Aston Martin.",
  },
  {
    id: "lance-stroll",
    number: 18,
    firstName: "Lance",
    lastName: "Stroll",
    team: "Aston Martin",
    teamId: "aston-martin",
    country: "Canada",
    countryFlag: "🇨🇦",
    dateOfBirth: "October 29, 1998",
    placeOfBirth: "Montreal, Canada",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#006F62",
    stats: { wins: 0, poles: 1, championships: 0, podiums: 3, fastestLaps: 0, points: 292 },
    careerHighlights: ["Youngest rookie podium (2017)", "Pole position at Turkey 2020", "F3 European Champion (2016)"],
    bio: "Lance Stroll is a solid midfield competitor with occasional flashes of brilliance. The Canadian continues to develop at Aston Martin alongside teammate Fernando Alonso.",
  },
  {
    id: "yuki-tsunoda",
    number: 22,
    firstName: "Yuki",
    lastName: "Tsunoda",
    team: "RB",
    teamId: "rb",
    country: "Japan",
    countryFlag: "🇯🇵",
    dateOfBirth: "May 11, 2000",
    placeOfBirth: "Sagamihara, Japan",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#6692FF",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 1, fastestLaps: 2, points: 91 },
    careerHighlights: ["First Japanese driver since Kobayashi", "F2 third place (2020)", "Honda protégé"],
    bio: "Yuki Tsunoda is a fiery competitor known for his aggressive racing and colorful team radio. The Japanese driver has shown flashes of speed at Racing Bulls.",
  },
  {
    id: "alexander-albon",
    number: 23,
    firstName: "Alexander",
    lastName: "Albon",
    team: "Williams",
    teamId: "williams",
    country: "Thailand",
    countryFlag: "🇹🇭",
    dateOfBirth: "March 23, 1996",
    placeOfBirth: "London, England",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#005AFF",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 2, fastestLaps: 0, points: 234 },
    careerHighlights: [
      "Former Red Bull driver",
      "Impressive performances for Williams",
      "Multiple points finishes in backmarker car",
    ],
    bio: "Alexander Albon made an impressive comeback to F1 with Williams after losing his Red Bull seat. The Thai-British driver consistently extracts maximum performance from his machinery.",
  },
  {
    id: "nico-hulkenberg",
    number: 27,
    firstName: "Nico",
    lastName: "Hülkenberg",
    team: "Sauber",
    teamId: "sauber",
    country: "Germany",
    countryFlag: "🇩🇪",
    dateOfBirth: "August 19, 1987",
    placeOfBirth: "Emmerich am Rhein, Germany",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#52E252",
    stats: { wins: 0, poles: 1, championships: 0, podiums: 0, fastestLaps: 2, points: 546 },
    careerHighlights: ["Brazil 2010 pole in rookie year", "Le Mans 24h winner", "Most races without a podium record"],
    bio: "Nico Hülkenberg returns to a full-time F1 seat with Sauber/Audi project. The German veteran brings valuable experience to the team's ambitious rebuilding effort.",
  },
  {
    id: "kevin-magnussen",
    number: 20,
    firstName: "Kevin",
    lastName: "Magnussen",
    team: "Haas",
    teamId: "haas",
    country: "Denmark",
    countryFlag: "🇩🇰",
    dateOfBirth: "October 5, 1992",
    placeOfBirth: "Roskilde, Denmark",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FFFFFF",
    stats: { wins: 0, poles: 1, championships: 0, podiums: 1, fastestLaps: 2, points: 185 },
    careerHighlights: ["Podium on F1 debut (2014)", "Sensational pole at Brazil 2022", "Son of Jan Magnussen"],
    bio: "Kevin Magnussen is a hard-nosed racer known for his wheel-to-wheel combat. The Dane's aggressive style makes him a formidable competitor in the midfield battles.",
  },
  {
    id: "pierre-gasly",
    number: 10,
    firstName: "Pierre",
    lastName: "Gasly",
    team: "Alpine",
    teamId: "alpine",
    country: "France",
    countryFlag: "🇫🇷",
    dateOfBirth: "February 7, 1996",
    placeOfBirth: "Rouen, France",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FF87BC",
    stats: { wins: 1, poles: 0, championships: 0, podiums: 4, fastestLaps: 3, points: 394 },
    careerHighlights: ["Monza 2020 victory", "Former Red Bull driver", "GP2 Champion (2016)"],
    bio: "Pierre Gasly showed incredible resilience after being demoted from Red Bull, winning at Monza in 2020. The Frenchman now leads Alpine's charge back up the grid.",
  },
  {
    id: "esteban-ocon",
    number: 31,
    firstName: "Esteban",
    lastName: "Ocon",
    team: "Alpine",
    teamId: "alpine",
    country: "France",
    countryFlag: "🇫🇷",
    dateOfBirth: "September 17, 1996",
    placeOfBirth: "Évreux, France",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FF87BC",
    stats: { wins: 1, poles: 0, championships: 0, podiums: 3, fastestLaps: 0, points: 435 },
    careerHighlights: ["Hungary 2021 maiden victory", "From karting with minimal budget to F1", "GP3 Champion (2015)"],
    bio: "Esteban Ocon is a tenacious racer who overcame financial hardship to reach Formula One. His determination and consistency have earned him respect throughout the paddock.",
  },
  {
    id: "valtteri-bottas",
    number: 77,
    firstName: "Valtteri",
    lastName: "Bottas",
    team: "Sauber",
    teamId: "sauber",
    country: "Finland",
    countryFlag: "🇫🇮",
    dateOfBirth: "August 28, 1989",
    placeOfBirth: "Nastola, Finland",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#52E252",
    stats: { wins: 10, poles: 20, championships: 0, podiums: 67, fastestLaps: 19, points: 1797 },
    careerHighlights: ["10 race victories", "5 years as Lewis Hamilton's teammate", "20 career pole positions"],
    bio: "Valtteri Bottas is a proven race winner with a decade of F1 experience. The Finnish driver brings crucial experience to Sauber as they prepare for Audi's arrival.",
  },
  {
    id: "zhou-guanyu",
    number: 24,
    firstName: "Zhou",
    lastName: "Guanyu",
    team: "Sauber",
    teamId: "sauber",
    country: "China",
    countryFlag: "🇨🇳",
    dateOfBirth: "May 30, 1999",
    placeOfBirth: "Shanghai, China",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#52E252",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 0, fastestLaps: 0, points: 12 },
    careerHighlights: [
      "First Chinese driver to score F1 points",
      "F2 third place (2021)",
      "Long Alpine academy career",
    ],
    bio: "Zhou Guanyu made history as China's first full-time F1 driver. The Shanghai native continues to develop his skills and represent his nation on the world stage.",
  },
  {
    id: "oliver-bearman",
    number: 87,
    firstName: "Oliver",
    lastName: "Bearman",
    team: "Haas",
    teamId: "haas",
    country: "United Kingdom",
    countryFlag: "🇬🇧",
    dateOfBirth: "May 8, 2005",
    placeOfBirth: "Chelmsford, England",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#FFFFFF",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 0, fastestLaps: 0, points: 7 },
    careerHighlights: ["Points on debut replacing Sainz", "F2 race winner", "Ferrari Driver Academy graduate"],
    bio: "Oliver Bearman is one of the most exciting young talents in Formula One. The British teenager impressed on his debut and now gets a full-time seat with Haas.",
  },
  {
    id: "kimi-antonelli",
    number: 12,
    firstName: "Kimi",
    lastName: "Antonelli",
    team: "Mercedes",
    teamId: "mercedes",
    country: "Italy",
    countryFlag: "🇮🇹",
    dateOfBirth: "August 25, 2006",
    placeOfBirth: "Bologna, Italy",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#00D2BE",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 0, fastestLaps: 0, points: 0 },
    careerHighlights: ["Mercedes junior program star", "F2 Champion (2024)", "Replaces Lewis Hamilton at Mercedes"],
    bio: "Kimi Antonelli is Mercedes' chosen one to replace Lewis Hamilton. The Italian prodigy has been fast-tracked through the junior categories and carries huge expectations.",
  },
  {
    id: "isack-hadjar",
    number: 6,
    firstName: "Isack",
    lastName: "Hadjar",
    team: "RB",
    teamId: "rb",
    country: "France",
    countryFlag: "🇫🇷",
    dateOfBirth: "September 28, 2004",
    placeOfBirth: "Paris, France",
    image: "/placeholder.svg?height=600&width=500",
    teamColor: "#6692FF",
    stats: { wins: 0, poles: 0, championships: 0, podiums: 0, fastestLaps: 0, points: 0 },
    careerHighlights: ["Red Bull junior program", "F2 race winner", "Multiple podiums in F2"],
    bio: "Isack Hadjar is a rising star from the Red Bull junior program. The French-Algerian driver impressed in F2 and earns his F1 debut with Racing Bulls.",
  },
]

export const allNews = [
  {
    id: "verstappen-qatar-gp",
    category: "RACE RESULTS",
    title: "Verstappen Dominates Qatar GP for Fourth Title",
    excerpt:
      "Max Verstappen secured his fourth consecutive World Championship with a commanding victory under the lights in Qatar.",
    content:
      "In a masterclass display of driving, Max Verstappen clinched his fourth consecutive World Championship at the Qatar Grand Prix. The Red Bull driver led from lights to flag, crossing the finish line 25 seconds ahead of his nearest rival. This championship cements his place among the all-time greats of Formula One.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Dec 1, 2025",
    author: "James Roberts",
    readTime: "5 min read",
  },
  {
    id: "hamilton-ferrari-confirmed",
    category: "TRANSFER NEWS",
    title: "Hamilton's Historic Move to Ferrari Confirmed",
    excerpt:
      "Seven-time champion Lewis Hamilton will join Scuderia Ferrari for the 2025 season in a blockbuster move that shocked the paddock.",
    content:
      "In the most stunning driver market move in decades, Lewis Hamilton has officially joined Scuderia Ferrari. The seven-time World Champion signed a multi-year deal to race for the Prancing Horse, ending his legendary partnership with Mercedes. Hamilton will partner Charles Leclerc in what many believe could be Ferrari's strongest lineup ever.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 28, 2025",
    author: "Sarah Mitchell",
    readTime: "7 min read",
  },
  {
    id: "2026-regulations",
    category: "TECHNICAL",
    title: "2026 Regulations: What You Need to Know",
    excerpt:
      "The FIA unveils major regulation changes for 2026, including new active aerodynamics and engine formulas that will reshape F1.",
    content:
      "The 2026 regulations represent the biggest technical reset in Formula One history. New active aerodynamics, sustainable fuels, and revamped power units will transform the sport. Teams are already investing hundreds of millions in preparation for this seismic shift.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 25, 2025",
    author: "David Chen",
    readTime: "10 min read",
  },
  {
    id: "mclaren-constructors",
    category: "CHAMPIONSHIP",
    title: "McLaren Wins First Constructors' Title Since 1998",
    excerpt:
      "McLaren Racing secured their first Constructors' Championship in 26 years with a dominant performance at the Abu Dhabi finale.",
    content:
      "McLaren's remarkable resurgence reached its peak with their first Constructors' Championship since Mika Häkkinen's era. Lando Norris and Oscar Piastri delivered consistent performances throughout the season, culminating in a championship-clinching 1-2 finish in Abu Dhabi.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 20, 2025",
    author: "Emma Thompson",
    readTime: "6 min read",
  },
  {
    id: "antonelli-mercedes",
    category: "DRIVER NEWS",
    title: "Antonelli: Mercedes' Teenage Sensation Ready for F1",
    excerpt:
      "18-year-old Kimi Antonelli prepares for his rookie F1 season with Mercedes, replacing seven-time champion Lewis Hamilton.",
    content:
      "Kimi Antonelli faces the unenviable task of replacing Lewis Hamilton at Mercedes, but the Italian teenager has shown he's up for the challenge. His dominant F2 campaign and impressive test performances have convinced Mercedes he's ready for the big stage.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 18, 2025",
    author: "Marco Rossi",
    readTime: "8 min read",
  },
  {
    id: "newey-aston-martin",
    category: "TECHNICAL",
    title: "Adrian Newey's Aston Martin Era Begins",
    excerpt:
      "Legendary designer Adrian Newey officially starts work at Aston Martin, bringing unprecedented technical expertise to the Silverstone outfit.",
    content:
      "Adrian Newey, the most successful designer in Formula One history, has begun his new chapter at Aston Martin. The British team's ambitious project to become World Champions received a massive boost with Newey's arrival.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 15, 2025",
    author: "Tom Williams",
    readTime: "5 min read",
  },
  {
    id: "las-vegas-gp-review",
    category: "RACE RESULTS",
    title: "Las Vegas GP: Leclerc Shines Under the Lights",
    excerpt:
      "Charles Leclerc delivered a stunning victory on the Las Vegas Strip, keeping his championship hopes alive with just two races remaining.",
    content:
      "Under the glittering lights of the Las Vegas Strip, Charles Leclerc produced one of the drives of the season. The Ferrari driver's tactical masterclass and tire management secured a crucial victory in F1's most glamorous race.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 12, 2025",
    author: "Michael Scott",
    readTime: "6 min read",
  },
  {
    id: "audi-sauber-progress",
    category: "TEAM NEWS",
    title: "Audi's F1 Project: Inside the Swiss Factory Revolution",
    excerpt:
      "Exclusive look at how Audi is transforming the Sauber facility in Hinwil ahead of their 2026 works team debut.",
    content:
      "Audi's ambitious Formula One project is taking shape in the Swiss Alps. The German manufacturer has invested over 500 million euros in transforming Sauber's Hinwil facility into a state-of-the-art F1 factory.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 10, 2025",
    author: "Hans Mueller",
    readTime: "9 min read",
  },
  {
    id: "sprint-format-changes",
    category: "REGULATIONS",
    title: "F1 Announces Expanded Sprint Race Format for 2026",
    excerpt:
      "Formula One confirms sprint races will feature at eight events in 2026, with revised points and qualifying formats.",
    content:
      "F1 has confirmed a significant expansion of the Sprint format for 2026. Eight events will feature the shortened race format, with revised points allocations and a new qualifying structure designed to increase on-track action.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 8, 2025",
    author: "Rachel Green",
    readTime: "4 min read",
  },
  {
    id: "red-bull-2026-engine",
    category: "TECHNICAL",
    title: "Red Bull Powertrains: The 2026 Engine Revealed",
    excerpt:
      "Red Bull lifts the lid on their first in-house Formula One power unit, developed in partnership with Ford.",
    content:
      "Red Bull has unveiled details of their 2026 power unit, the first engine developed entirely in-house at their Milton Keynes facility. The Ford-badged unit represents a massive technical undertaking for the championship-winning team.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 5, 2025",
    author: "James Roberts",
    readTime: "7 min read",
  },
  {
    id: "thailand-gp-confirmed",
    category: "CALENDAR",
    title: "Thailand Joins 2026 F1 Calendar with Bangkok Street Race",
    excerpt:
      "Formula One confirms Thailand will host a street race in Bangkok from 2026, expanding F1's presence in Southeast Asia.",
    content:
      "Thailand will join the Formula One calendar in 2026 with an ambitious street circuit in the heart of Bangkok. The race will strengthen F1's presence in Southeast Asia and bring the sport to one of the world's most vibrant cities.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 2, 2025",
    author: "Somchai Patel",
    readTime: "5 min read",
  },
  {
    id: "f1-viewership-record",
    category: "BUSINESS",
    title: "F1 Breaks Global Viewership Records in 2025",
    excerpt:
      "Formula One announces record-breaking television and streaming viewership figures, with the sport reaching over 1.5 billion viewers worldwide.",
    content:
      "Formula One has achieved its highest viewership figures in history, with over 1.5 billion cumulative viewers tuning in during the 2025 season. The sport's popularity continues to surge, driven by the Netflix effect and thrilling on-track action.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Oct 30, 2025",
    author: "Lisa Anderson",
    readTime: "4 min read",
  },
  {
    id: "abu-dhabi-season-finale",
    category: "RACE PREVIEW",
    title: "Abu Dhabi Season Finale: What's at Stake",
    excerpt:
      "The constructors' championship goes down to the wire as McLaren and Ferrari battle for glory under the lights.",
    content:
      "The Abu Dhabi Grand Prix will decide the 2025 Constructors' Championship in what promises to be a thrilling season finale. McLaren leads Ferrari by just 41 points heading into the final race at Yas Marina Circuit. Both teams have everything to play for in this winner-takes-all showdown.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Dec 5, 2025",
    author: "Michael Chen",
    readTime: "6 min read",
  },
  {
    id: "norris-breakout-season",
    category: "DRIVER FOCUS",
    title: "Lando Norris: A Star is Born",
    excerpt: "How the McLaren driver emerged as a genuine championship contender in 2025.",
    content:
      "Lando Norris has finally fulfilled his immense potential this season, winning four races and mounting a genuine championship challenge. The 26-year-old Briton has matured into one of the grid's best drivers, combining blistering pace with newfound consistency and racecraft.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 25, 2025",
    author: "Emma Wilson",
    readTime: "8 min read",
  },
  {
    id: "2026-regulations",
    category: "REGULATIONS",
    title: "2026 Regulations: Everything You Need to Know",
    excerpt: "F1's next revolution promises to shake up the order with radical new power units and aerodynamics.",
    content:
      "Formula 1 will undergo its biggest technical revolution since 2014 with the introduction of new regulations in 2026. The sport will feature completely new power units with increased electrical power, active aerodynamics, and lighter cars. Teams are already deep into development of their 2026 challengers.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 20, 2025",
    author: "David Thompson",
    readTime: "10 min read",
  },
  {
    id: "rookie-sensations",
    category: "ROOKIES",
    title: "The Rookie Class Making Waves",
    excerpt: "Antonelli, Bearman, and Hadjar bring fresh energy to the 2025 grid.",
    content:
      "The 2025 season has seen an influx of exciting young talent to Formula 1. Mercedes' Kimi Antonelli, Haas' Oliver Bearman, and Racing Bulls' Isack Hadjar represent the next generation of F1 stars. All three rookies have shown flashes of brilliance in their debut seasons.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 15, 2025",
    author: "Sophie Anderson",
    readTime: "7 min read",
  },
  {
    id: "ferrari-resurgence",
    category: "TEAM ANALYSIS",
    title: "Ferrari's Fight Back: Inside the Resurgence",
    excerpt: "How the Scuderia rediscovered its winning ways in the second half of 2025.",
    content:
      "Ferrari's transformation in the latter half of 2025 has been remarkable. Technical upgrades introduced at the British Grand Prix unlocked significant performance, allowing Charles Leclerc and Lewis Hamilton to fight for victories consistently. The Prancing Horse is back.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 10, 2025",
    author: "Marco Rossi",
    readTime: "9 min read",
  },
  {
    id: "las-vegas-russell-masterclass",
    category: "RACE RESULTS",
    title: "Russell's Vegas Masterclass Stuns the Grid",
    excerpt: "George Russell delivered a perfect drive to win the Las Vegas Grand Prix in commanding fashion.",
    content:
      "George Russell produced the drive of his life to win the Las Vegas Grand Prix, leading every lap and setting the fastest lap. The Mercedes driver's flawless performance under the bright lights of Sin City marked his third career victory and proved he's ready to lead the Silver Arrows.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 24, 2025",
    author: "Chris Martinez",
    readTime: "6 min read",
  },
  {
    id: "alonso-still-got-it",
    category: "DRIVER FOCUS",
    title: "Alonso Proves Age is Just a Number",
    excerpt: "At 44, Fernando Alonso continues to show why he's one of F1's all-time greats.",
    content:
      "Fernando Alonso's performances in 2025 have been nothing short of remarkable. The two-time World Champion has consistently outperformed his Aston Martin machinery, extracting every ounce of performance and keeping much younger rivals honest. His hunger and skill remain as sharp as ever.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Nov 5, 2025",
    author: "Laura Garcia",
    readTime: "7 min read",
  },
  {
    id: "red-bull-dominance-ends",
    category: "TECHNICAL",
    title: "How Red Bull Lost Their Advantage",
    excerpt: "Technical analysis of Red Bull's decline and their rivals' catch-up.",
    content:
      "Red Bull's period of dominance came to an end in 2025 as rivals McLaren and Ferrari caught up on development. The RB21 struggled with balance issues mid-season, and despite updates, the team couldn't maintain their performance edge. This analysis breaks down what went wrong.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Oct 30, 2025",
    author: "Technical Team",
    readTime: "12 min read",
  },
  {
    id: "sprint-format-debate",
    category: "OPINION",
    title: "Sprint Races: Love Them or Hate Them?",
    excerpt: "The ongoing debate about F1's sprint format continues to divide fans and teams.",
    content:
      "Sprint races remain one of Formula 1's most controversial innovations. While they provide additional action on race weekends, many argue they detract from the traditional grand prix format. We examine both sides of this heated debate with input from drivers, team principals, and fans.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Oct 25, 2025",
    author: "Opinion Desk",
    readTime: "8 min read",
  },
  {
    id: "williams-resurgence",
    category: "TEAM ANALYSIS",
    title: "Williams Racing Returns to Competitiveness",
    excerpt: "James Vowles' leadership is transforming the historic British team.",
    content:
      "Williams Racing has made significant strides under team principal James Vowles. The arrival of Carlos Sainz and major technical investments are paying dividends, with the team regularly fighting for points. This marks a remarkable turnaround for one of F1's most storied constructors.",
    image: "/placeholder.svg?height=600&width=1000",
    date: "Oct 20, 2025",
    author: "Paul Richards",
    readTime: "9 min read",
  },
]
